# Generated by Django 2.1.5 on 2019-01-13 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DnsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.TextField(verbose_name='host')),
                ('type', models.TextField(verbose_name='dns type')),
                ('log_time', models.DateTimeField(auto_now_add=True, verbose_name='time loged')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['log_time'],
            },
        ),
        migrations.CreateModel(
            name='UserSubDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.CharField(max_length=128)),
                ('status', models.IntegerField(verbose_name='status')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='time added')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['add_time'],
            },
        ),
        migrations.CreateModel(
            name='WebLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='remote_addr')),
                ('path', models.TextField(verbose_name='path')),
                ('header', models.TextField(verbose_name='header')),
                ('body', models.TextField(verbose_name='body')),
                ('log_time', models.DateTimeField(auto_now_add=True, verbose_name='time loged')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['log_time'],
            },
        ),
    ]
